02/10/21 (22:47:56) | ERROR: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
03/10/21 (15:32:24) | ERROR: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
03/10/21 (15:37:28) | ERROR: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
03/10/21 (18:07:25) | ERROR: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
03/10/21 (18:09:31) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/sbin/bpytop", line 985, in _get_key
    input_key = ""
  File "/sbin/bpytop", line 778, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
08/10/21 (00:32:24) | ERROR: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
10/10/21 (21:39:02) | ERROR: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
10/10/21 (21:48:29) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/sbin/bpytop", line 985, in _get_key
    input_key = ""
  File "/sbin/bpytop", line 778, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
10/10/21 (23:05:03) | ERROR: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/arch/.config/bpytop/themes'
